                                        ;(1 3 (5 7) 9)
                                        ;((7))
                                        ;(1 (2 (3 (4 (5 (6 7))))))
(define list-1 (list 1 3 (list 5 7) 9))
(define list-2 (list (list 7)))
(define list-3 (list 1 (list 2 (list 3 (list 4 (list 5 (list 6 7)))))))

(car (cdaddr list-1))
(caar list-2)
(cadadr (cadadr (cadadr list-3)))
